import Footer from "@/ui/Footer";
import Header from "@/ui/Header/Header";
import Loader from "@/ui/Loader/Loader";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AOSInit } from "./aos";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "RC - Karts",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AOSInit />
      <body className={inter.className}>
        <Header />
        {children}
        <Loader />
        <Footer />
      </body>
    </html>
  );
}
